// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// C is an autogenerated mock type for the C type
type C struct {
	mock.Mock
}

type C_Expecter struct {
	mock *mock.Mock
}

func (_m *C) EXPECT() *C_Expecter {
	return &C_Expecter{mock: &_m.Mock}
}

// FuncA provides a mock function with given fields:
func (_m *C) FuncA() {
	_m.Called()
}

// C_FuncA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FuncA'
type C_FuncA_Call struct {
	*mock.Call
}

// FuncA is a helper method to define mock.On call
func (_e *C_Expecter) FuncA() *C_FuncA_Call {
	return &C_FuncA_Call{Call: _e.mock.On("FuncA")}
}

func (_c *C_FuncA_Call) Run(run func()) *C_FuncA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *C_FuncA_Call) Return() *C_FuncA_Call {
	_c.Call.Return()
	return _c
}

func (_c *C_FuncA_Call) RunAndReturn(run func()) *C_FuncA_Call {
	_c.Call.Return(run)
	return _c
}

// NewC creates a new instance of C. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewC(t interface {
	mock.TestingT
	Cleanup(func())
}) *C {
	mock := &C{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
